### ISSUE TITLE
issue #1 : 회원가입 중 프로필 사진 입력 시, 오류 발생

### ISSUE THREAD

**Issue by wheeze01** [Likelion12-KNU-potato-programmers/Real_GongGamHae_Frontend#1]
오류명 : 
The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential. (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: QWTE9YJ9V6ZZMVRG; S3 Extended Request ID: fLHZsx0ADsmOrIm+FEKoXjN0BdPQWZUnmUlPpSgNmr/ieGjExQob/rsIn5NAKOVzP9xg5vrP7zJOTGszrfozMw==; Proxy: null)

사진이 포함되지 않으면 회원가입은 정상적으로 작동됩니다.

제 로컬 환경에서 설정이 잘못되어 제쪽에서만 그러는건지 확인 해주시면 감사합니다.
![스크린샷 2024-06-01 212528](https://github.com/Likelion12-KNU-potato-programmers/Real_GongGamHae_Frontend/assets/54202163/fe7759b9-767e-46a9-b9fa-0ce7cc16c9fa)

**Comment by GamJaDo** [comment]
스프링 서버의 application.yml 파일에 s3(이미지 저장 서버)의 키값이 없어서 뜬 오류 같습니다. repository에 올릴 때 보안상 이유로 키를 뺏었던 것 같은데 갠톡 주시면 키값을 드리겠습니다.
